# Generated by Django 6.1 on 2026-08-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='FinancialForecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_month', models.DateField()),
                ('predicted_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predicted_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('generated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'financial_forecasts',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(max_length=50)),
                ('merchant', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('transaction_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.account')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='FraudPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('fraud_probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('prediction', models.BooleanField()),
                ('model_version', models.CharField(max_length=100)),
                ('predicted_at', models.DateTimeField()),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.transaction')),
            ],
            options={
                'db_table': 'fraud_predictions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.branch')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('ip_address', models.CharField(max_length=45)),
                ('log_time', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.user')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.user'),
        ),
    ]
