# Generated by Django 6.1 on 2026-08-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_is_anomaly_alert_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_anomaly',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Generated', max_length=50)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='finance.user')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
