# Generated by Django 6.1 on 2026-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_is_anomaly_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ifsc_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
