# Generated by Django 6.1 on 2026-08-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_branch_branch_name_alter_branch_ifsc_code_and_more'),
        ('finance', '0005_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
    ]
